# Generated by Django 2.2 on 2020-03-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TagsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='标签名')),
            ],
        ),
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('path', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='博客相对路径')),
                ('categories', models.CharField(max_length=50, verbose_name='博客分类')),
                ('is_valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_mathjax', models.BooleanField(default=False, verbose_name='是否启用 mathjax 数学公式')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='是否允许评论')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否首页置顶（需配合 hexo-generator-index-pin-top 使用）')),
                ('layout', models.CharField(default='single-column', max_length=100, verbose_name='是否单列（Next 模板无需设置）')),
                ('is_toc', models.BooleanField(default=True, verbose_name='是否展示目录（Next 模板无需设置）')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('description', models.CharField(max_length=1000, verbose_name='博客描述')),
                ('content', models.TextField(max_length=50000, verbose_name='博客内容')),
                ('tags', models.ManyToManyField(to='web.TagsModel', verbose_name='博客标签')),
            ],
        ),
    ]
