# Generated by Django 2.2 on 2020-03-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='博客分类'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(blank=True, max_length=50000, null=True, verbose_name='博客内容'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='博客描述'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='web.TagsModel', verbose_name='博客标签'),
        ),
    ]
