# Generated by Django 2.2 on 2020-03-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200308_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='web.TagsModel', verbose_name='博客标签'),
        ),
    ]
