# Generated by Django 2.2 on 2020-03-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200308_1158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoriesmodel',
            old_name='category',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='categoriesmodel',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AddField(
            model_name='tagsmodel',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='是否有效'),
        ),
        migrations.AlterField(
            model_name='categoriesmodel',
            name='wrapper_folder',
            field=models.CharField(max_length=100, unique=True, verbose_name='外层文件夹名'),
        ),
    ]
