# Generated by Django 2.2 on 2020-03-08 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20200308_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='web.CategoriesModel', verbose_name='博客分类'),
        ),
    ]
