"""
Django settings for hexo_migrator project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@(smtcxz*u+_6a=$lxusc=#mq40)l$j*kdj412+r%@@ko#6a$-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'web',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'web.middlewares.auth.AuthMiddleware'
]

ROOT_URLCONF = 'hexo_migrator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hexo_migrator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',    # 使用 MySQL 数据库
        'NAME': 'hexo',    # 数据库名
        'HOST': '127.0.0.1',    # 数据库 IP
        'PORT': 3306,    # 数据库端口
        'USER': 'root',   # 登录数据库使用的用户名
        'PASSWORD': '123'    # 登录数据库使用的密码
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/hexostatic/'
STATIC_ROOT = '/tmp/hexo_static'

# Hexo Migrator 主逻辑中的相关配置
# BLOG_BASE_DIR = os.path.join(BASE_DIR, 'main_logic', 'test')    # 博客原文根路径
# BLOG_GEN_DIR = os.path.join(BASE_DIR, 'main_logic', 'test2')    # 生成的博客路径
# DEFAULT_OLD_DIR = os.path.join(BASE_DIR, 'main_logic', 'test2')    # 要导入的
# BLOG_BASE_DIR = r'C:\Users\Sure\PyProject\神器\技术查阅手册'    # 博客原文根路径
# BLOG_GEN_DIR = r'C:\Users\Sure\PyProject\神器\技术查阅手册3'    # 生成的博客路径
# DEFAULT_OLD_DIR = r'C:\Users\Sure\PyProject\神器\技术查阅手册3'    # 要导入的旧的已经生成好的博客路径
BLOG_BASE_DIR = r'/data/PyProject/神器/技术查阅手册'    # 博客原文根路径
BLOG_GEN_DIR = r'/tmp/hexo/source/_posts'    # 生成的博客路径
DEFAULT_OLD_DIR = r'/data/blog'    # 要导入的旧的已经生成好的博客路径

# 需要忽略的文件或文件夹名（暂不支持正则）
FILE_IGNORE = ['.git', '.gitignore', '.idea', '.vscode']


# 外层文件夹和分类对应字典，批量导入分类时会用到
CATEGORY_DICT = {
    '': '首页',
    'bug-bible': 'Bug 宝典',
    'database': '数据库',
    'linux': 'Linux',
    'notes': '学习实践笔记',
    'python-advanced': 'Python 进阶',
    'python-basic': 'Python 基础',
    'raspberry-pi': '树莓派',
    'testing': '测试',
    'translation': '官方文档翻译',
    'web': 'Web',
    'django': 'Django',
    'project': '综合项目',
    'git': 'Git',
    'hexo': 'Hexo',
}

# 各种正则规则

YAML_STR_RE = "^---\n.+?\n---\n\n"    # Front Matter 正则，匹配时需要设置 DOTALL
TITLE_RE = '^#{1,3} .+?\n'    # 标题正则
CODE_BLOCK_RE = '\n\\s*?```.*?\n\\s*?```\n'    # 代码块正则，匹配时需要设置 DOTALL
TOC_RE_LIST = [    # 匹配 [TOC]
    '\n[toc]\n',
    '\n[Toc]\n',
    '\n[tOc]\n',
    '\n[toC]\n',
    '\n[TOc]\n',
    '\n[ToC]\n',
    '\n[tOC]\n',
    '\n[TOC]\n',
]
PARAGRAPH_RE = '\n#+ .+?\n'
BRACE_RE_LIST_NORMAL = ['{{', '}}', '{#', '#}']
BRACE_RE_LIST_STRANGE = '{%.*?%}'    # 因为要使用 {% raw %} 转义括号，所以处理 {% %} 要稍麻烦一些，稍有不慎可能无限递归
BRACE_RE_STRANGE_LEFT = '{%'
BRACE_RE_STRANGE_RIGHT = '%}'
BRACE_RE_SAFE = '{% raw %}.*?{% endraw %}'

IMG_RE_LIST = [
    {'tag': '!\\[.+?\\]\\(.+?[.]assets.+?\\..+?\\)', 'file_name': '!\\[.+?\\]\\(.+?[.]assets.(.+?\\..+?)\\)'},
    {'tag': '<img src = .+?\\.assets.+?\\..+?>', 'file_name': '<img src = .+?\\.assets.(.+?\\..+?).>'},
]

LINK_RE = '\\[.+?\\]\\(.*?\\.md[\\)#]'

HEXO_ABS_PATH = '/root/.nvm/versions/node/v10.15.2/bin/hexo'    # Hexo 启动文件的绝对路径
HEXO_BASE_DIR = '/tmp/hexo'
HEXO_ALGOLIA_INDEXING_KEY='eb82f2e78e3053f26aa408e9caa96d93'

CMD_LIST = [
    HEXO_ABS_PATH,
    '--cwd',
    HEXO_BASE_DIR,
    'clean',
    '&&',
    HEXO_ABS_PATH,
    '--cwd',
    HEXO_BASE_DIR,
    'generate',
    '-d',
    '&&',
    'export',
    f'HEXO_ALGOLIA_INDEXING_KEY={HEXO_ALGOLIA_INDEXING_KEY}',
    '&&',
    HEXO_ABS_PATH,
    '--cwd',
    HEXO_BASE_DIR,
    'algolia',
]

